alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - alertmanager.magnifikboutique.online
    paths:
      - /
    pathType: Prefix
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - grafana.magnifikboutique.online
    paths:
      - /
    pathType: Prefix
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - prometheus.magnifikboutique.online
    paths:
      - /
    pathType: Prefix
  prometheusSpec:
    externalUrl: http://prometheus.magnifikboutique.online
    resources:
      limits:
        memory: 500Mi
        cpu: 200m
      requests:
        memory: 200Mi
        cpu: 30m
