apiVersion: v1
kind: Service
metadata:
  name: velero
  namespace: velero
  labels:
      component: velero
      deploy: velero
spec:
  selector:
    component: velero
    deploy: velero
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
    name: metrics
