# create Servicemonitor to scrape velero metrics
# for prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: velero
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      component: velero
      deploy: velero
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    any: true
